.github/workflows/sonarqube.yml

fix: sonarqube fix

---

.github/workflows/production.yml

build: Update production.yml

---

README.md
docs/CODEOWNERS.md

docs: added codeowners.md

---

README.md

docs: update README.md []

---

.github/workflows/production.yml
deploymentManifests/deployment.yml

refactor: deployment update

---

.github/workflows/development/development.yml

build: Development

---

src/modules/common/models/workspace.model.ts
src/modules/identity/controllers/team.controller.ts
src/modules/identity/payloads/team.payload.ts
src/modules/identity/repositories/team.repository.ts
src/modules/identity/services/team-user.service.ts
src/modules/identity/services/team.service.ts
src/modules/workspace/payloads/workspace.payload.ts
src/modules/workspace/services/workspace-user.service.ts
src/modules/workspace/services/workspace.service.ts

feat: Update workspace model and Add Team Update API[]

---

src/modules/common/models/team.model.ts
src/modules/identity/controllers/team.controller.ts
src/modules/identity/payloads/user.payload.ts
src/modules/identity/services/team-user.service.ts
src/modules/identity/services/team.service.ts

Introduce a feature called the 'NEW INVITE' tag functionality, designed specifically for teams that have recently been invited. This feature aims to enhance the user experience by visually highlighting and categorizing teams that have received recent invitations, thereby providing a clear and distinguishable marker for newly invited teams within the system.

feat: Introduce 'NEW INVITE' tag functionality for newly invited teams.

---

src/modules/identity/payloads/register.payload.ts
src/modules/identity/services/user.service.ts

Introduce password validation while user registration

feat: introduce password validation while user registration

---

src/modules/identity/services/auth.service.ts

This PR adds user name in token payload which is required for profile icon initial fix .

feat: add name in token payload

---

src/modules/common/enum/topic.enum.ts

fix: Remove unwanted comment[]

---

src/modules/workspace/payloads/collection.payload.ts
src/modules/workspace/payloads/collectionRequest.payload.ts
src/modules/workspace/services/collection-request.service.ts

Fix - Collection description not updating.

fix: collection description not updating

---

src/modules/common/services/parser.service.ts
src/modules/workspace/controllers/workspace.controller.ts

fix: swagger url parsing[]

---

src/modules/identity/controllers/user.controller.ts
src/modules/identity/payloads/user.payload.ts
src/modules/identity/services/user.service.ts

implement registered user status api. which returns the result weather user registered with email or oAuth

feat: implement registered user status api

---

src/modules/common/enum/database.collection.enum.ts
src/modules/common/models/feature.model.ts
src/modules/workspace/controllers/feature.controller.ts
src/modules/workspace/payloads/feature.payload.ts
src/modules/workspace/repositories/feature.repository.ts
src/modules/workspace/services/feature.service.ts
src/modules/workspace/workspace.module.ts

Added POST, GET, PUT, DELETE APIs for Feature.

feat: Added Feature APIs []

---

src/modules/app/app.controller.ts
src/modules/common/models/collection.model.ts
src/modules/common/services/parser.service.ts
src/modules/workspace/controllers/workspace.controller.ts
src/modules/workspace/repositories/collection.repository.ts
src/modules/workspace/repositories/workspace.repository.ts
src/modules/workspace/services/collection.service.ts

add activeSync and activeSyncUrl
- [] 🍕 Feature

fix: importUrl active sync

---

src/modules/common/services/parser.service.ts
src/modules/workspace/controllers/workspace.controller.ts
src/modules/workspace/repositories/collection.repository.ts

This PR fixes the importUrl API

fix: featch activeSync Collection[]

---

src/modules/workspace/repositories/collection.repository.ts

fix: handle case where 1st active sync collection is made[]

---

src/modules/common/models/collection.model.ts
src/modules/workspace/payloads/collectionRequest.payload.ts

This PR adds the below feature 
It adds auth info to request when it is saved.

feat: add auth info while saving api request[]

---

src/modules/common/models/user.model.ts
src/modules/identity/controllers/user.controller.ts
src/modules/identity/payloads/resetPassword.payload.ts
src/modules/identity/repositories/user.repository.ts
src/modules/identity/services/user.service.ts

implement verification code auth at change password

feat: implement verification code auth at change password

---

src/modules/app/app.controller.ts
src/modules/app/app.service.ts
src/modules/app/payloads/app.payload.ts
tsconfig.json

Taking curl in body and not headers .
Changes tsconfig to fix docker build.

Fix: docker build[]

---

src/modules/app/app.controller.ts
src/modules/common/models/branch.model.ts
src/modules/common/models/collection.model.ts
src/modules/common/services/helper/parser.helper.ts
src/modules/common/services/parser.service.ts
src/modules/workspace/controllers/collection.controller.ts
src/modules/workspace/controllers/workspace.controller.ts
src/modules/workspace/payloads/branch.payload.ts
src/modules/workspace/payloads/collection.payload.ts
src/modules/workspace/repositories/branch.repository.ts
src/modules/workspace/repositories/collection.repository.ts
src/modules/workspace/services/branch.service.ts
src/modules/workspace/services/collection.service.ts

Added branch logic for active sync.
Added get collection items according to branch selected(switch branch logic).
add validate-oapi api

feat: added branch logic[]

---

src/modules/app/app.controller.ts
src/modules/app/app.service.ts
src/modules/app/payloads/app.payload.ts
src/modules/common/services/parser.service.ts
src/modules/workspace/payloads/collection.payload.ts
tsconfig.json

This PR fixes Validate OAPI API

fix: validate oapi api[]

---

src/modules/workspace/payloads/workspace.payload.ts

The fixes the update workspace issue.

fix: users set to null on workspace update[]

---

src/modules/common/config/configuration.ts
src/modules/workspace/payloads/branch.payload.ts
src/modules/workspace/repositories/branch.repository.ts
src/modules/workspace/services/branch.service.ts
src/modules/workspace/services/collection.service.ts

Added logic to remove already deleted api's which are more than 7 days old.

feat: Added deleted logic for API []

---

src/modules/identity/controllers/team.controller.ts
src/modules/identity/controllers/user.controller.ts
src/modules/identity/repositories/team.repository.ts
src/modules/identity/repositories/user.repository.ts
src/modules/identity/services/team.service.ts
src/modules/identity/services/user.service.ts
src/modules/workspace/controllers/collection.controller.ts
src/modules/workspace/controllers/environment.controller.ts
src/modules/workspace/controllers/workspace.controller.ts
src/modules/workspace/repositories/collection.repository.ts
src/modules/workspace/repositories/environment.repository.ts
src/modules/workspace/repositories/workspace.repository.ts
src/modules/workspace/services/collection-request.service.ts
src/modules/workspace/services/collection.service.ts
src/modules/workspace/services/environment.service.ts
src/modules/workspace/services/workspace.service.ts

Added Partial type to payloads of all update functions to avoid unwanted behaviours and remove update anomalies.

fix: add Partial type to payloads of all update functions[]

---

src/modules/common/services/parser.service.ts
src/modules/workspace/controllers/workspace.controller.ts
src/modules/workspace/payloads/collection.payload.ts

Fixed the issue about fetching local host URL at server side, now taking it from user.

fix: Fixed localhost Url issue in importurl []

---

src/modules/workspace/controllers/workspace.controller.ts

Added url again so that it can be saved in collection.

fix: Added misisng url field []

---

src/modules/workspace/controllers/collection.controller.ts
src/modules/workspace/services/collection.service.ts

Fixed - collection being created with items as null.

fix: create collection[]

---

src/modules/app/app.controller.ts
src/modules/app/app.service.ts
src/modules/workspace/controllers/collection.controller.ts
src/modules/workspace/payloads/collectionRequest.payload.ts

Removed branchname from path params and added to body

fix: Replaced branch name param []

---

src/modules/common/models/collection.model.ts
src/modules/common/services/parser.service.ts
src/modules/workspace/controllers/workspace.controller.ts
src/modules/workspace/payloads/collection.payload.ts

Added local repository path in collection

feat: Added local repo path []

---

src/modules/workspace/controllers/collection.controller.ts
src/modules/workspace/payloads/collectionRequest.payload.ts
src/modules/workspace/repositories/branch.repository.ts
src/modules/workspace/services/collection-request.service.ts

Added functionality to add folder and request on particular branches in case of active sync

fix: Added folder and request in branches []

---

src/modules/common/services/parser.service.ts

Fixed issue in importurl after adding single request.

fix: fixed crash on add request []

---

src/modules/app/app.service.ts
src/modules/workspace/services/collection.service.ts

Added function to remove extra line space and casing in curl import

fix: fixed curl import for some curls []

---

src/modules/common/services/helper/oapi2.transformer.ts
src/modules/common/services/helper/oapi3.transformer.ts

Added source property in folder for imported collection through URL

fix: added source at folder level []

---

src/modules/app/app.controller.ts
src/modules/app/app.service.ts
src/modules/app/payloads/curl.payload.ts

Changed the request type to application/x-www-form-urlencoded and updated the swagger

fix: Fixed the curl request body issue []

---

src/modules/common/services/helper/oapi2.transformer.ts
src/modules/common/services/helper/oapi3.transformer.ts

Fixed the issue of all the Request not importing in importUrl, now all the URLs will get imported even with same end point.

fix: Request count issue in import

---

src/modules/common/models/collection.model.ts
src/modules/common/services/parser.service.ts
src/modules/workspace/repositories/collection.repository.ts

FIxed the id and name requirement of updatedBy details

fix: Add name and id in updatedBy at collection []

---

src/modules/workspace/services/collection.service.ts

fix: no permission logout [716]

---

src/modules/common/config/configuration.ts
src/modules/identity/services/team.service.ts
src/modules/workspace/handlers/workspace.handler.ts
src/modules/workspace/payloads/workspace.payload.ts
src/modules/workspace/services/workspace.service.ts

Fixed workspace not creating in first try by kafka consumer, added timeout to fix this so when consumer calls the workspace create function the value message will be be undefined.

fix: fixed workspace not creating by kafka consumer

---

src/modules/common/enum/error-messages.enum.ts
src/modules/common/models/feedback.model.ts
src/modules/workspace/payloads/feedback.payload.ts
src/modules/workspace/services/feedback.service.ts

Removed PDF file support in feedback files and made sub category as optional

fix: removed pdf support and made sub category optional []

---

src/main.ts

Increased fastify multipart file size limit to 50MB

fix: increased fastify multipart file size limit []

---

src/modules/app/app.service.ts
src/modules/common/services/helper/oapi2.transformer.ts
src/modules/common/services/helper/oapi3.transformer.ts

fixed import collection freeze issue by stringifying param value and added documentation and removed unnecessary encoding check

fix: stringified query values and added documentation []

---

src/modules/identity/controllers/user.controller.ts
src/modules/identity/services/auth.service.ts
src/modules/identity/services/user.service.ts

fixed case sensitivity issue of email

fix: made email non case sensitive []

---

src/modules/common/services/helper/oapi3.transformer.ts

fix: open api security check

---

deploymentManifests/deployment.yml

build: updated new ENV of FEEDBACK_BLOB_CONTAINER

---

src/modules/app/app.controller.ts
src/modules/workspace/controllers/feature.controller.ts

Remove auth guard from curl and feaature

fix: remove auth guard from curl and feature []

---

src/modules/workspace/services/environment.service.ts

fixed global env updates point.

fix: global environment update bug []

---

src/modules/common/services/helper/oapi3.transformer.ts

fix: fixed import collection for oapi 3.1 [#1231]

---

src/modules/identity/services/team-user.service.ts
src/modules/workspace/services/workspace.service.ts

made email non case sensitive in invite flow of team and workspace

fix: made email non case sensitive in invite flow []

---

src/modules/identity/services/team-user.service.ts

Admin can changes another admins permissions

fix: admin permission changes []

---

src/modules/identity/services/team-user.service.ts

fix: fixed member not removing issue []

---

deploymentManifests/deployment.yml

build: Added new ENV

---

src/modules/workspace/services/workspace.service.ts

fixed bug on multiple user not adding in workspace

fix: multiple user not adding in workspace []

---

src/modules/common/config/configuration.ts
src/modules/common/services/email.service.ts
src/modules/identity/services/team-user.service.ts
src/modules/identity/services/user.service.ts
src/modules/views/addTeamAdminEmail.handlebars
src/modules/views/demoteEditorEmail.handlebars
src/modules/views/demoteTeamAdminEmail.handlebars
src/modules/views/inviteTeamEmail.handlebars
src/modules/views/inviteWorkspaceEmail.handlebars
src/modules/views/leaveTeamEmail.handlebars
src/modules/views/newOwnerEmail.handlebars
src/modules/views/newWorkspaceEmail.handlebars
src/modules/views/oldOwnerEmail.handlebars
src/modules/views/partials/footer.handlebars
src/modules/views/partials/header.handlebars
src/modules/views/promoteViewerEmail.handlebars
src/modules/views/removeUserEmail.handlebars
src/modules/views/signUpEmail.handlebars
src/modules/views/verifyEmail.handlebars
src/modules/workspace/services/workspace.service.ts

#1209 #1210
In this i have added email template for inviting user in workspace  also  solved bugs overall  in the email template

Feat: Added workspace invite email template & solved bugs

---

src/modules/identity/services/team-user.service.ts
src/modules/identity/services/user.service.ts
src/modules/views/inviteWorkspaceEmail.handlebars
src/modules/views/newOwnerEmail.handlebars
src/modules/views/oldOwnerEmail.handlebars
src/modules/views/partials/footer.handlebars
src/modules/views/promoteViewerEmail.handlebars
src/modules/views/removeUserEmail.handlebars
src/modules/views/signUpEmail.handlebars
src/modules/workspace/services/workspace.service.ts

#1341
In this PR i have solved the UI bugs in the email templates

fix: Fixed email template UI bugs

---

src/modules/views/addTeamAdminEmail.handlebars
src/modules/views/inviteTeamEmail.handlebars
src/modules/views/inviteWorkspaceEmail.handlebars
src/modules/views/oldOwnerEmail.handlebars
src/modules/views/promoteViewerEmail.handlebars
src/modules/views/signUpEmail.handlebars

#1341
In this PR i have added the class to some p tag that fixes the size of  text.

Fix:  Fixed Text size in email template

---

src/modules/identity/controllers/auth.controller.ts

saved data properly at context at create user

fix: fixed break at create user []

---

src/modules/identity/strategies/google.strategy.ts

Added prompt property with consecnt and select account to force user to choose account.

fix: added prompt for force account choose []

---

src/modules/common/config/configuration.ts
src/modules/common/models/collection.model.ts
src/modules/identity/services/team-user.service.ts
src/modules/identity/services/user.service.ts
src/modules/workspace/controllers/collection.controller.ts
src/modules/workspace/payloads/collectionRequest.payload.ts
src/modules/workspace/repositories/collection.repository.ts
src/modules/workspace/services/collection-request.service.ts

This PR consists of the CRUD apis for the web socket flow including:-
- Add a websocket
- update a websocket 
- - delete a websocket

feat: web socket apis []

---

deploymentManifests/deployment.yml

fix: fixed key in deplyoment yml []

---

src/modules/workspace/controllers/feedback.controller.ts
src/modules/workspace/services/feedback.service.ts

Added svg support, removed video support and updated data in uploads API

fix: updated supported files for feedback images []
